# Generated by Django 3.1.3 on 2020-12-04 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_type', models.CharField(blank=True, choices=[('room clean after checkout', '1'), ('room clean by client request', '2'), ('room clean by complain', '3'), ('delivery amenity', 'A'), ('delivery client goods', 'B'), ('add extra bed', 'C'), ('other', 'Other')], max_length=30)),
                ('complain_message', models.CharField(max_length=100)),
                ('complain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complain_type')),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
