# Generated by Django 3.1.3 on 2020-12-05 10:49

import complaints.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain_type',
            fields=[
                ('complain_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complain_number', models.IntegerField(default=complaints.models.Complain.number, max_length=6, primary_key=True, serialize=False)),
                ('customer_ID', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem_type', models.CharField(blank=True, choices=[('1', 'room clean after checkout'), ('2', 'room clean by client request'), ('3', 'room clean by complain'), ('A', 'delivery amenity'), ('B', 'delivery client things'), ('C', 'add extra bed'), ('other', 'Other')], max_length=30)),
                ('complain_message', models.CharField(max_length=100)),
                ('complain_code', models.CharField(blank=True, max_length=20, null=True)),
                ('complain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complain_type')),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
