# Generated by Django 3.1.3 on 2020-12-02 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complain_type', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('employee_ID', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('complain_message', models.CharField(max_length=100)),
            ],
        ),
    ]
