# Generated by Django 3.1.3 on 2020-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('1', 'room clean after checkout'), ('2', 'room clean by client request'), ('3', 'room clean by complain'), ('A', 'delivery amenity'), ('B', 'delivery client things'), ('C', 'add extra bed'), ('other', 'Other')], max_length=30),
        ),
    ]
