# Generated by Django 3.1.3 on 2020-12-05 10:50

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_number',
            field=models.CharField(default=complaints.models.Complain.number, max_length=6, primary_key=True, serialize=False),
        ),
    ]
