# Generated by Django 3.1.3 on 2020-11-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work_type', models.CharField(blank=True, choices=[('houseman', 'Houseman'), ('londry', 'Londry'), ('operator', 'Operator'), ('reception', 'Reception'), ('reservation', 'Reservation'), ('roommaid', 'Room maid'), ('other', 'Other')], max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
