# Generated by Django 3.1.3 on 2020-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_ID', models.CharField(max_length=100)),
                ('e_name', models.CharField(max_length=80)),
                ('e_type', models.CharField(blank=True, choices=[('houseman', 'Houseman'), ('londry', 'Londry'), ('operator', 'Operator'), ('reception', 'Reception'), ('reservation', 'Reservation'), ('roommaid', 'Roommaid')], max_length=80)),
                ('e_birthdate', models.DateField(blank=True, null=True)),
                ('e_address', models.CharField(max_length=140)),
                ('e_salary', models.IntegerField()),
                ('e_phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
