# Generated by Django 3.1.3 on 2020-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_complain_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_PW',
            field=models.CharField(max_length=300),
        ),
    ]
