# Generated by Django 3.1.3 on 2020-11-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20201129_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ID',
            new_name='e_ID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='e_PW',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birthdate',
            new_name='e_birthdate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='e_salary',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='work_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='e_address',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_phone_number',
            field=models.CharField(default='000-0000-0000', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='e_work_type',
            field=models.CharField(blank=True, choices=[('houseman', 'Houseman'), ('londry', 'Londry'), ('operator', 'Operator'), ('reception', 'Reception'), ('reservation', 'Reservation'), ('roommaid', 'Room maid'), ('other', 'Other')], max_length=20),
        ),
    ]
